<?php
require('client.inc.php');
$errors=array();
//page
$nav->setActiveNav('new');
require(CLIENTINC_DIR.'header.inc.php');
require(CLIENTINC_DIR.'nothirdparty.inc.php');
require(CLIENTINC_DIR.'footer.inc.php');
?>
